### ISSUE TITLE
Tech Tips - videos don't play

### ISSUE THREAD

**Issue by kevinjscott** [scteisbe/sctemobile#10]
I don't think you can play YouTube videos directly within the <video> tag, but there are a couple other options:

Use a library...
http://mediaelementjs.com/examples/?name=youtube

Use an iframe (assuming this can go full screen???)...
https://www.thepolyglotdeveloper.com/2015/01/embed-video-ios-android-ionicframework-app/

..Kev

**Comment by surojitpakira** [comment]
fixed and deployed
