### ISSUE TITLE
Blog #2: NCTA

### ISSUE THREAD

**Issue by kevinjscott** [scteisbe/sctemobile#105]
Pretty much the same as the one we just did for CableLabs / Informed. Preview 3 posts, "see all" goes to full list, etc. The 3 items section can be right below the CableLabs section.

- [ ] Section header logo image: https://www.ncta.com/sites/prod/files/NCTA-Horizontal.png
- [ ] RSS feed: https://www.ncta.com/platform/feed/
- [ ] Image for each article can be taken from the embedded Twitter metadata e.g. `<meta name="twitter:image" content="https://www.ncta.com/platform/wp-content/uploads/2016/07/EnBancHeader.png" />`

**Comment by surojitpakira** [comment]
Fixed and deployed
