### ISSUE TITLE
Change CableLabs blog logo

### ISSUE THREAD

**Issue by kevinjscott** [scteisbe/sctemobile#106]
Please use this one instead - http://www.scte.org/images/Logos/cablelabs.png

**Comment by surojitpakira** [comment]
fixed and deployed

**Comment by kevinjscott** [comment]
I'm still seeing the grey "INFORM[ED]" logo.

**Comment by kevinjscott** [comment]
Oh, I see the misunderstanding. This was supposed to change the blog logo from "INFORM[ED]" to red "CableLabs". The CableLabs logo in the Resources tab was not supposed to be changed. Please change it back to black as it was before. Thanks.

**Comment by surojitpakira** [comment]
Fixed and deployed
