### ISSUE TITLE
New tab icons

### ISSUE THREAD

**Issue by kevinjscott** [scteisbe/sctemobile#107]
Discover: Search_Icon_White.png
My Learning: MyLearning_Icon_White.png
Tech Tips: TechTips_Icon_White.png
Toolkit: Toolkit_Icon_White.png
Resources: TechResources_Icon_White.png

[Archive.zip](https://github.com/scteisbe/sctemobile/files/401728/Archive.zip)

**Comment by surojitpakira** [comment]
Fixed and deployed
