### ISSUE TITLE
Wrong data source for TechTips

### ISSUE THREAD

**Issue by kevinjscott** [scteisbe/sctemobile#13]
From the Google Doc sheet `techtips`, the list view should be using the `subtitle` field, not `htmlbody` or `plaintextbody`.

Once the user clicks "more info," the content should come from the `htmlbody` field. We may deprecate the `plaintextbody` field (not currently used anywhere).

![image](https://cloud.githubusercontent.com/assets/132882/16049087/75efb542-3224-11e6-9bf7-30b7dffbe8a1.png)

**Comment by surojitpakira** [comment]
fixed and deployed
