### ISSUE TITLE
Subnav tabs not displaying correctly

### ISSUE THREAD

**Issue by kevinjscott** [scteisbe/sctemobile#19]
I see this on Android device, not Chrome. I'm not sure about iPhone device.

Vertical padding is missing e.g. "g" in progress is cut off. Last letter "s" is also cut off slightly.

![image](https://cloud.githubusercontent.com/assets/132882/16316146/0d21ed4c-3953-11e6-8844-937aade321cc.png)

**Comment by surojitpakira** [comment]
fixed and deployed
