### ISSUE TITLE
Harmonize the appearance of lists across the app

### ISSUE THREAD

**Issue by kevinjscott** [scteisbe/sctemobile#24]
Variance in list styles / shapes / colors needs to be reduced. For example:

* Consistent background color
* Consistent header/title color and font
* Consistent border and/or separator
* Consistent width
* Consistent font sizes, colors, and weights

**Comment by surojitpakira** [comment]
Fixed and deployed

**Comment by surojitpakira** [comment]
Fixed and deployed
