### ISSUE TITLE
Harmonize the top part of views - need a proposal

### ISSUE THREAD

**Issue by kevinjscott** [scteisbe/sctemobile#25]
This issue refers to the combined use of the blue header and the scrollable top section of the view e.g.

![image](https://cloud.githubusercontent.com/assets/132882/16337971/72cc0abc-39e7-11e6-8f1f-e833f73b6cde.png)

![image](https://cloud.githubusercontent.com/assets/132882/16337897/d03f50f6-39e6-11e6-99c9-ae72463cc2a4.png)

![image](https://cloud.githubusercontent.com/assets/132882/16337902/dbcf6a46-39e6-11e6-9030-182f19698ac8.png)

![image](https://cloud.githubusercontent.com/assets/132882/16337914/f19eef18-39e6-11e6-8cc3-226734b0284b.png)

Please bring some consistency to how we use this space. We don't necessarily need a paragraph at the top of any page. We may or may not need the tab title repeated at the top and/or in the blue header.

Please propose how we will resolve this.

**Comment by surojitpakira** [comment]
Fixed and deployed !!
