### ISSUE TITLE
Change TechTip submit TO: address

### ISSUE THREAD

**Issue by kevinjscott** [scteisbe/sctemobile#26]
During testing, we want to use a different email address. While we're doing that, let's make it configurable so we can easily change it back for launch.

Use the value from the staticdata Google sheet "configs": https://docs.google.com/spreadsheets/d/1KTe0AcWPrApY8qOzTV_lJrftDxo0ZDRB7DYtzZfvFLY/edit#gid=1011695050

submit_tech_tip_email_address

**Comment by surojitpakira** [comment]
Please retest and reopen if still exists !!
