### ISSUE TITLE
HTML techtips disappear after being viewed

### ISSUE THREAD

**Issue by kevinjscott** [scteisbe/sctemobile#33]
![image](https://cloud.githubusercontent.com/assets/132882/16632964/e4a9230c-4394-11e6-9a5b-50532aa03b46.png)

![image](https://cloud.githubusercontent.com/assets/132882/16632994/0dd80716-4395-11e6-9a4d-be160cb51744.png)

**Comment by surojitpakira** [comment]
Fixed and deployed
