### ISSUE TITLE
<title> tag is being incorrectly set

### ISSUE THREAD

**Issue by kevinjscott** [scteisbe/sctemobile#34]
The page title is used by default by the analytics libraries, so needs to contain a proper title for the tab.

Should be set for every view including detailed content views i.e. a specific tech tip or event detail view.

![image](https://cloud.githubusercontent.com/assets/132882/16639542/75da12d6-43be-11e6-83a4-7bb775d3d8f1.png)

**Comment by surojitpakira** [comment]
Fixed and deployed

**Comment by kevinjscott** [comment]
Reopening - maybe the title is being set at the wrong time? It's not showing up correctly in Google Analytics.

![image](https://cloud.githubusercontent.com/assets/132882/16846112/2fd34856-49b9-11e6-9e5d-9d6fcfc53705.png)

**Comment by surojitpakira** [comment]
Please reset and let me know if it works.

**Comment by surojitpakira** [comment]
Fixed and deployed
