### ISSUE TITLE
Tech Tip submit needs styling

### ISSUE THREAD

**Issue by kevinjscott** [scteisbe/sctemobile#38]
The current style doesn't match iOS or Android. Should it be full screen? Correct spelling is "Tech Tip".  URL field should be a single line input with autocapitalize turned off. Please also include a short paragraph of lorem ipsum between the header and the first field as a placeholder for instructions.

![image](https://cloud.githubusercontent.com/assets/132882/16666040/e6acc5fe-4453-11e6-8127-93f2c0f97e40.png)

**Comment by surojitpakira** [comment]
Fixed and deployed
