### ISSUE TITLE
Webinar tweaks

### ISSUE THREAD

**Issue by kevinjscott** [scteisbe/sctemobile#68]
1. Please change the header from "ARCHIVED WEBINARS" to "PREVIOUS WEBINARS"
2. Replace the document icon with an icon that has something to do with webinar e.g. has a "play" icon as part of it. The icons I found online tend to show a PC, which doesn't seem quite right. Anyhow, see if you can find something that works.

**Comment by surojitpakira** [comment]
Completed and deployed
