### ISSUE TITLE
Tech Tips - video thumbnail styling

### ISSUE THREAD

**Issue by kevinjscott** [scteisbe/sctemobile#7]
You can load the <video> tag without the controls (or hidden). Use JS to start playback on thumbnail tap and then add the controls http://www.w3schools.com/tags/av_prop_controls.asp

Eventually, playback should be fullscreen landscape and the controls aren't nearly as obtrusive in that mode.

We can optimize all this later. For now, the main priority is to hide the controls initially so the full thumbnail is visible (ok to keep the "play" triangle).

![skitch](https://cloud.githubusercontent.com/assets/132882/16021633/bcc84428-3181-11e6-8693-7d80a6162a46.png)

**Comment by surojitpakira** [comment]
fixed and deployed
