### ISSUE TITLE
CableLabs blog entries

### ISSUE THREAD

**Issue by kevinjscott** [scteisbe/sctemobile#70]
Read RSS from http://www.cablelabs.com/feed

Display 3 entries and a "see all" link below the events section on the Discover tab.

Section header should just be this image http://www.cablelabs.com/wp-content/themes/cablelabs-v23/images/Informed-CL-logo-1200x350.png

**Comment by surojitpakira** [comment]
fixed and deployed

**Comment by kevinjscott** [comment]
Icons in list view should respect the aspect ratio of the image.

**Comment by surojitpakira** [comment]
fixed and deployed
