### ISSUE TITLE
CableLabs specs

### ISSUE THREAD

**Issue by kevinjscott** [scteisbe/sctemobile#71]
Scrape specs from http://www.cablelabs.com/specs/specification-search. They should all just be PDF files.

In the Resources tab:
* Show 1 most recent CableLabs document (based on publish date)
* Then show 2 most recent SCTE documents (based on "sortid" in Google Sheet static data feed)

Change section header from "SCTE STANDARDS" to "STANDARDS AND SPECIFICATIONS"

Show the SCTE logo as the image for items from SCTE. Show a CableLabs logo for those from CableLabs - http://www.cablelabs.com/wp-content/uploads/2014/05/CAB_logo_BW.png

Sorting in "show all" view:
* Include both sets of documents into one list
* Sort by title (not ID or identifier) ascending

**Comment by surojitpakira** [comment]
Thumbnail needs to be fixed across the app.
Everything else fixed and deployed
