### ISSUE TITLE
My Learning empty state

### ISSUE THREAD

**Issue by kevinjscott** [scteisbe/sctemobile#81]
- [ ] Move the "no results" text up above the button
- [ ] All courses: "You haven't enrolled in any courses. Check out all the learning opportunities available to you in the SCTE / ISBE Course Catalog!"
- [ ] In progress: "You don't have any courses in progress. Check out all the learning opportunities available to you in the SCTE / ISBE Course Catalog!"
- [ ] Completed: "You haven't completed any courses yet."

![image](https://cloud.githubusercontent.com/assets/132882/17112164/e873c7d4-5272-11e6-93c5-f9b256db9ca3.png)

**Comment by surojitpakira** [comment]
fixed and deployed
