### ISSUE TITLE
iCohere courses

### ISSUE THREAD

**Issue by kevinjscott** [scteisbe/sctemobile#84]
Many SCTE members will not have any learning plans in WCW. Instead, they will still have their learning materials in the legacy system, called iCohere. Those are out of scope for this project, but we still need to respect the data.

If a course exists in the data with no child modules under it, please handle as shown below. The "not available" text should not be clickable.

![image](https://cloud.githubusercontent.com/assets/132882/17213796/ee96f568-54a3-11e6-81fa-d55aca496241.png)

**Comment by surojitpakira** [comment]
fixed and deployed. But, no test data currently to test in real app.
