### ISSUE TITLE
Changes to Discover header bar

### ISSUE THREAD

**Issue by kevinjscott** [scteisbe/sctemobile#87]
- [ ] Remove the "Hello, Tester" text and the avatar icon
- [ ] If co-branding logo URL does not exist, center the gear brain icon in the header area (like on other tabs)
- [ ] If co-branding logo exists, center co-brand logo in the header area and show gear brain icon on left side
- [ ] Make the "tap to see app info" function work if you tap on the gear brain icon

**Comment by surojitpakira** [comment]
fixed and deployed

**Comment by kevinjscott** [comment]
Co-brand logo should be centered on the entire screen width...not just the space to the right of the gear brain icon. Currently, it's sitting a bit right of center.

**Comment by surojitpakira** [comment]
fixed and deployed
