### ISSUE TITLE
Handling Inkling content in search results

### ISSUE THREAD

**Issue by kevinjscott** [scteisbe/sctemobile#89]
Inkling content will be FTP'd or downloaded somewhere inside of SharePoint and then crawled for search indexing. That means any item from Inkling will be easily identifiable by its URL pattern. Either the Web API or the client needs to act on that to identify Inkling content.

In the app, if the user taps on an Inkling item in the search results, open a dialog with a title of `Inkling Axis`:
> This course material is available in the Inkling Axis app. Once you have it installed, you'll be able to read it there.

`Cancel` `Continue`

On Android, open `https://play.google.com/store/apps/details?id=com.inkling.android.axis&hl=en`

On iOS, open `https://itunes.apple.com/us/app/inkling-axis/id923550071?mt=8`

There is no content-specific action to be taken. The Inkling app doesn't support universal links or deeplinking, so all we need to do is take users to the app.

If we can detect that the app is installed, great...please take them directly to the app. If not, then we'll just have to send them to the store links above.

**Comment by surojitpakira** [comment]
It will open the app store directly.
fixed and deployed
