### ISSUE TITLE
Show more app info before ellipsis "..."

### ISSUE THREAD

**Issue by kevinjscott** [scteisbe/sctemobile#9]
App library list needs multiple lines before ellipsis. Max 2 lines for title, max 3 lines for description. Also, please use some of the whitespace on the right.

![image](https://cloud.githubusercontent.com/assets/132882/16021689/0cad4bc8-3182-11e6-98cc-3bb07ce2f09e.png)

**Comment by surojitpakira** [comment]
fixed and deployed
