### ISSUE TITLE
Make the Discover header grey

### ISSUE THREAD

**Issue by kevinjscott** [scteisbe/sctemobile#92]
Change the blue at the top of the Discover tab to be the same grey background as the rest of the page. Keep tab buttons at the bottom as blue. Give the rounded input box a little blue border (same blue as bottom tabs).

![image](https://cloud.githubusercontent.com/assets/132882/17260138/b96d6594-559c-11e6-9eef-05740414193a.png)

**Comment by surojitpakira** [comment]
Fixed and deployed
