### ISSUE TITLE
Icons for intro screens

### ISSUE THREAD

**Issue by kevinjscott** [scteisbe/sctemobile#94]
Here are the actual icons to use for cards 2-4 [Archive.zip](https://github.com/scteisbe/sctemobile/files/394105/Archive.zip)

![image](https://cloud.githubusercontent.com/assets/132882/17298282/43b28662-57d7-11e6-809a-eb36f4e75072.png)

Card 2:
![cortex_app_icon_group1](https://cloud.githubusercontent.com/assets/132882/17298204/fd7ef4aa-57d6-11e6-8ee4-3408dc067a9d.png)

Card 3:
![cortex_app_icon_group2](https://cloud.githubusercontent.com/assets/132882/17298231/15d53e42-57d7-11e6-9909-1e529919f11e.png)

Card 4 (I think you already have this one):
![cortex_app_icon_group3](https://cloud.githubusercontent.com/assets/132882/17298251/231dbd18-57d7-11e6-8732-d41278c712da.png)

**Comment by surojitpakira** [comment]
fixed and deployed
