### ISSUE TITLE
Incorrect cobranding logic

### ISSUE THREAD

**Issue by kevinjscott** [scteisbe/sctemobile#97]
If I delete the logourls from this sheet where each "Spectrum" co-branding logo appears and then restart the app, it still appears in the header. If the URL is empty in that static data feed or if the company ID isn't in the sheet at all, the app should be in non-cobrand mode i.e. just the gear brain logo.

**Comment by surojitpakira** [comment]
fixed and deployed

**Comment by kevinjscott** [comment]
Should update the next time I open the app.

Looks like it gets the update after restart, but doesn't show it until app is restarted a second time or user switches tabs and goes back to Discover.

**Comment by surojitpakira** [comment]
As we discussed, it can't be accommodate both local storage and live change.
