### ISSUE TITLE
Intro screens - Cortex logo is not clear

### ISSUE THREAD

**Issue by kevinjscott** [scteisbe/sctemobile#99]
![image](https://cloud.githubusercontent.com/assets/132882/17306525/77a77a78-57fe-11e6-82e0-dda3a1ae134a.png)

**Comment by kevinjscott** [comment]
I just realized that you may not have a higher resolution version of this. I have requested it and will provide it to you ASAP.

**Comment by kevinjscott** [comment]
Here you go! Includes the original source .ai file in case you need other resolutions.

[CORTEX LOGO.zip](https://github.com/scteisbe/sctemobile/files/397001/CORTEX.LOGO.zip)

**Comment by surojitpakira** [comment]
fixed and deployed
